albumy/blueprints/auth.py
# -*- coding: utf-8 -*-

from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user, login_fresh

from albumy.emails import send_reset_password_email
from albumy.extensions import db
from albumy.forms.auth import LoginForm, RegisterForm, ForgetPasswordForm, ResetPasswordForm
from albumy.models import User
from albumy.settings import Operations
from albumy.utils import generate_token, validate_token, redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('Login success.', 'info')
                
                # Check if the user is a farmer and redirect accordingly
                if user.is_farmer:
                    return redirect(url_for('user.index', username=current_user.username))
                else:
                    return redirect(url_for('main.explore'))
                
            else:
                flash('Your account is blocked.', 'warning')
                return redirect(url_for('main.index'))
        flash('Invalid email or password.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/re-authenticate', methods=['GET', 'POST'])
@login_required
def re_authenticate():
    if login_fresh():
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        return redirect_back()
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        print(form.data)
        name = form.name.data
        email = form.email.data.lower()
        username = form.username.data
        password = form.password.data
        user = User(name=name, email=email, username=username)
        user.is_farmer = form.is_farmer.data
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)

@auth_bp.route('/forget-password', methods=['GET', 'POST'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)
            flash('Password reset email sent, check your inbox.', 'info')
            return redirect(url_for('.login'))
        flash('Invalid email.', 'warning')
        return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is None:
            return redirect(url_for('main.index'))
        if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD,
                          new_password=form.password.data):
            flash('Password updated.', 'success')
            return redirect(url_for('.login'))
        else:
            flash('Invalid or expired link.', 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)

albumy/blueprints/main.py
# -*- coding: utf-8 -*-

import os
import random
from dotenv import load_dotenv
from urllib.parse import urlencode
import openai
import re
import requests
from flask import session
import re

from flask import render_template, flash, redirect, url_for, current_app, \
    send_from_directory, request, abort, Blueprint
from flask_login import login_required, current_user
from sqlalchemy.sql.expression import func

from albumy.decorators import permission_required
from albumy.extensions import db
from albumy.forms.main import DescriptionForm, TagForm, CommentForm
from albumy.models import User, Photo, Tag, Follow, Collect, Comment, Notification
from albumy.notifications import push_comment_notification, push_collect_notification
from albumy.utils import rename_image, resize_image, redirect_back, flash_errors

main_bp = Blueprint('main', __name__)

@main_bp.route('/index')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['ALBUMY_PHOTO_PER_PAGE']
        pagination = Photo.query \
            .join(Follow, Follow.followed_id == Photo.author_id) \
            .filter(Follow.follower_id == current_user.id) \
            .order_by(Photo.timestamp.desc()) \
            .paginate(page, per_page)
        photos = pagination.items
    else:
        pagination = None
        photos = None
    tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(func.count(Photo.id).desc()).limit(10)
    return render_template('main/index.html', pagination=pagination, photos=photos, tags=tags, Collect=Collect)

@main_bp.route('/')
@main_bp.route('/explore')
def explore():
    photos = Photo.query.order_by(func.random()).limit(12)
    return render_template('main/explore.html', photos=photos)


from google.cloud import vision_v1
from google.cloud.vision_v1 import types
from werkzeug.utils import secure_filename
import os

UPLOAD_FOLDER = 'uploads'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def get_ingredients_from_image(image_path, confidence_threshold=0.7):
    try:
        client = vision_v1.ImageAnnotatorClient()
        with open(image_path, 'rb') as image_file:
            content = image_file.read()
        image = types.Image(content=content)
        response = client.label_detection(image=image)
        
        common_fridge_items = set([
            "egg", "milk", "cheese", "yogurt", "butter", "bread", "chicken", "beef", 
            "pork", "fish", "tomato", "onion", "garlic", "lettuce", "spinach", "carrot", 
            "broccoli", "apple", "orange", "banana", "grape", "berry", "chocolate", "juice", 
            "water",
            # ... (expand this list as needed)
        ])

        detected_items = [
            label.description.lower() for label in response.label_annotations 
            if label.score >= confidence_threshold and label.description.lower() in common_fridge_items
        ]
        
        return detected_items
    
    except Exception as e:
        print(f"Error processing image: {e}")
        return ['eggs', 'tomatoes', 'spinach', 'milk']

load_dotenv()

# Initialize the OpenAI API with your key
openai.api_key = os.getenv("OPENAPI_KEY")

@main_bp.route('/make_meal', methods=['GET', 'POST'])
@login_required
def make_meal():
    recipe_details = None
    if request.method == 'POST':
        file = request.files['file']
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            filepath = os.path.join(UPLOAD_FOLDER, filename)
            file.save(filepath)
            ingredients = get_ingredients_from_image(filepath)
        else:
            ingredients = ['eggs', 'tomatoes', 'spinach', 'milk']
        description = request.form.get('description')

        initial_message = {
            "role": "user",
            "content": f"I have these in my fridge: {', '.join(ingredients)}. I want to make a {description}. Format: 'Ingredients:' followed by ingredients separated by '$', then 'Steps:' followed by the numbered steps separated by '$'."
        }

        gpt_response = run_conversation_with_gpt([initial_message])
        response_text = gpt_response.get('choices', [{}])[0].get('message', {}).get('content', '').strip()

        # Default empty lists
        ingredients_list = []
        instructions_list = []

        # Parsing
        if "Ingredients:" in response_text and "Steps:" in response_text:
            ingredients_text = response_text.split("Ingredients:")[1].split("Steps:")[0].strip()
            instructions_text = response_text.split("Steps:")[1].strip()

            # Split ingredients based on '$' symbol
            ingredients_list = [item.strip() for item in ingredients_text.split('$') if item.strip()]
            ingredients_list = [(i + " ✓") if i in ingredients else i for i in ingredients_list]
            
            # Split steps and remove any leading numbers followed by a dollar sign
            instructions_list = [re.sub(r"^\d+\.\s?", "", step).strip() for step in instructions_text.split('\n') if step.strip()]
        recipe_details = {
            'ingredients': ingredients_list,
            'instructions': instructions_list
        }
                
    return render_template('main/make_meal.html', recipe=recipe_details)

@main_bp.route('/help', methods=['GET'])
@login_required  # If you want to require the user to be logged in to access this route, otherwise, remove this line.
def help():
    return render_template('main/help.html')

def run_conversation_with_gpt(messages):
    # Set up the call to GPT-3.5-turbo-0613
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo-0613",
        messages=messages,
    )
    return response

@main_bp.route('/search')
def search():
    q = request.args.get('q', '').strip()
    if q == '':
        flash('Enter keyword about photo, user or tag.', 'warning')
        return redirect_back()

    category = request.args.get('category', 'photo')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_SEARCH_RESULT_PER_PAGE']
    if category == 'user':
        pagination = User.query.whooshee_search(q).paginate(page, per_page)
    elif category == 'tag':
        pagination = Tag.query.whooshee_search(q).paginate(page, per_page)
    else:
        pagination = Photo.query.whooshee_search(q).paginate(page, per_page)
    results = pagination.items
    return render_template('main/search.html', q=q, results=results, pagination=pagination, category=category)


@main_bp.route('/notifications')
@login_required
def show_notifications():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_NOTIFICATION_PER_PAGE']
    notifications = Notification.query.with_parent(current_user)
    filter_rule = request.args.get('filter')
    if filter_rule == 'unread':
        notifications = notifications.filter_by(is_read=False)

    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(page, per_page)
    notifications = pagination.items
    return render_template('main/notifications.html', pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if current_user != notification.receiver:
        abort(403)

    notification.is_read = True
    db.session.commit()
    flash('Notification archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/notifications/read/all', methods=['POST'])
@login_required
def read_all_notification():
    for notification in current_user.notifications:
        notification.is_read = True
    db.session.commit()
    flash('All notifications archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['ALBUMY_UPLOAD_PATH'], filename)


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
@permission_required('UPLOAD')
def upload():
    if request.method == 'POST' and 'file' in request.files:
        f = request.files.get('file')
        filename = rename_image(f.filename)
        f.save(os.path.join(current_app.config['ALBUMY_UPLOAD_PATH'], filename))
        filename_s = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['small'])
        filename_m = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['medium'])
        
        # Get additional form data
        location = request.form.get('location')
        quantity = request.form.get('quantity')
        produce_name = request.form.get('produce_name')
        price = request.form.get('price')
        
        photo = Photo(
            filename=filename,
            filename_s=filename_s,
            filename_m=filename_m,
            author=current_user._get_current_object(),
            location=location,  # Save location
            quantity=quantity,  # Save quantity
            produce_name=produce_name,  # Save produce_name
            price=price  # Save price
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')


@main_bp.route('/photo/<int:photo_id>')
def show_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(photo).order_by(Comment.timestamp.asc()).paginate(page, per_page)
    comments = pagination.items

albumy/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
        <title>{% block title %}{% endblock %} - Misfit</title>
        <link rel="shortcut icon" href="{{ url_for('static', filename='icon.ico') }}">
        {% block styles %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        {% endblock styles %}
    {% endblock head %}
</head>

<body>
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.explore') }}">
                <img src="{{ url_for('static', filename='icon.ico') }}" alt="Misfit">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('main.explore', 'Explore') }}
                    {{ render_nav_item('main.help', 'Help') }}
                </div>
                <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('main.upload') }}" title="Upload">
                        <span class="oi oi-cloud-upload"></span>&nbsp;&nbsp;
                    </a>
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                            <img class="avatar-xs"
                                 src="{{ url_for('main.get_avatar', filename=current_user.avatar_s) }}">
                            <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <h6 class="dropdown-header">Logged in as {{ current_user.username }}</h6>
                            <a class="dropdown-item" href="{{ url_for('user.index', username=current_user.username) }}">
                                <span class="oi oi-person"></span> My Home
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('user.edit_profile') }}">
                                <span class="oi oi-cog"></span> Settings
                            </a>
                            {% if current_user.can('MODERATE') %}
                                <a class="dropdown-item" href="{{ url_for('admin.index') }}">
                                    <span class="oi oi-dashboard"></span> Dashboard
                                </a>
                            {% endif %}
                            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                <span class="oi oi-power-standby"></span> Logout
                            </a>
                        </div>
                    </div>
                {% else %}
                <a class="btn btn-outline-primary" href="{{ url_for('auth.login') }}" style="background-color: #FFFFFF; color: #8c9474; border-color: #8c9474;">Login</a>&nbsp;&nbsp;
<a class="btn btn-primary" href="{{ url_for('auth.register') }}" style="background-color: #8c9474; color: #FFFFFF; border-color: #8c9474; transition: background-color 0.3s, border-color 0.3s;">Join Misfit</a></a>{% endif %}
                </div>
            </div>
        </div>
    </nav>
{% endblock %}

<main>
    <div class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}
        {% block content %}{% endblock %}
        {% block footer %}
            <footer>
                <p class="float-left">
                    <small>&copy; 2023
                        <a href="" title="Written by Munchers @ HackHarvard">Misfit Munch</a>
                    </small>
                </p>
                <p class="float-right">
                    <small>A new era for food sustainability.</small>
                </p>
            </footer>
        {% endblock %}
    </div>
</main>
<div id="toast"></div>

{% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script type="text/javascript">
        var csrf_token = "{{ csrf_token() }}";
        {% if current_user.is_authenticated %}
            var is_authenticated = true;
        {% else %}
            var is_authenticated = false;
        {% endif %}
    </script>
{% endblock %}
</body>
</html>

albumy/templates/macros.html
{% macro photo_card(photo) %}
    <div class="photo-card card">
        <a class="card-thumbnail" href="{{ url_for('main.show_photo', photo_id=photo.id) }}">
            <img class="card-img-top portrait" src="{{ url_for('main.get_image', filename=photo.filename_s) }}">
        </a>
        <div class="card-body">
            <!-- Display Produce Name -->
            <h3 class="d-inline-block"><strong>{{ photo.produce_name }}</strong></h3>
            
            <!-- Display Location with map marker icon -->
            <p><span class="oi oi-map-marker"></span> {{ photo.location }}</p>
            
            <!-- Clear float for following content -->
            <div style="clear: both;"></div>
            
            <!-- Display Price -->
            <p>(${{ photo.price }} / Lb)</p>
            
            <!-- Display Quantity -->
            <p style="color: red;">{{ photo.quantity }} pounds left</p>
        </div>
    </div>
{% endmacro %}

{% macro user_card(user) %}
    <div class="user-card text-center">
        <a href="{{ url_for('user.index', username=user.username) }}">
            <img class="rounded avatar-m" src="{{ url_for('main.get_avatar', filename=user.avatar_m) }}">
        </a>
        <h6>
            <a href="{{ url_for('user.index', username=user.username) }}">{{ user.name }}</a>
        </h6>
        {{ follow_area(user) }}
    </div>
{% endmacro %}

{% macro follow_area(user) %}
    {% if current_user.is_authenticated %}
        {% if user != current_user %}
            {% if current_user.is_following(user) %}
                <form class="inline" method="post"
                      action="{{ url_for('user.unfollow', username=user.username, next=request.full_path) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-dark btn-sm">Unfollow</button>
                    {% if current_user.is_followed_by(user) %}
                        <p class="badge badge-light">Follow each other</p>
                    {% endif %}
                </form>
            {% else %}
                <form class="inline" method="post"
                      action="{{ url_for('user.follow', username=user.username, next=request.full_path) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-primary btn-sm">Follow</button>
                    {% if current_user.is_followed_by(user) %}
                        <p class="badge badge-light">Follows you</p>
                    {% endif %}
                </form>
            {% endif %}
        {% endif %}
    {% else %}
        <form class="inline" method="post"
              action="{{ url_for('user.follow', username=user.username) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-primary btn-sm">Follow</button>
        </form>
    {% endif %}
{% endmacro %}