albumy/blueprints/ajax.py
# -*- coding: utf-8 -*-

from flask import render_template, jsonify, Blueprint
from flask_login import current_user

from albumy.models import User, Photo, Notification
from albumy.notifications import push_collect_notification, push_follow_notification

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/notifications-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)


@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/followers-count/<int:user_id>')
def followers_count(user_id):
    user = User.query.get_or_404(user_id)
    count = user.followers.count() - 1  # minus user self
    return jsonify(count=count)


@ajax_bp.route('/<int:photo_id>/followers-count')
def collectors_count(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    count = len(photo.collectors)
    return jsonify(count=count)


@ajax_bp.route('/collect/<int:photo_id>', methods=['POST'])
def collect(photo_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    if not current_user.can('COLLECT'):
        return jsonify(message='No permission.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if current_user.is_collecting(photo):
        return jsonify(message='Already collected.'), 400

    current_user.collect(photo)
    if current_user != photo.author and photo.author.receive_collect_notification:
        push_collect_notification(collector=current_user, photo_id=photo_id, receiver=photo.author)
    return jsonify(message='Photo collected.')


@ajax_bp.route('/uncollect/<int:photo_id>', methods=['POST'])
def uncollect(photo_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if not current_user.is_collecting(photo):
        return jsonify(message='Not collect yet.'), 400

    current_user.uncollect(photo)
    return jsonify(message='Collect canceled.')


@ajax_bp.route('/follow/<username>', methods=['POST'])
def follow(username):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    if not current_user.can('FOLLOW'):
        return jsonify(message='No permission.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        return jsonify(message='Already followed.'), 400

    current_user.follow(user)
    if user.receive_collect_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return jsonify(message='User followed.')


@ajax_bp.route('/unfollow/<username>', methods=['POST'])
def unfollow(username):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_following(user):
        return jsonify(message='Not follow yet.'), 400

    current_user.unfollow(user)
    return jsonify(message='Follow canceled.')

albumy/blueprints/auth.py
# -*- coding: utf-8 -*-

from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user, login_fresh

from albumy.emails import send_reset_password_email
from albumy.extensions import db
from albumy.forms.auth import LoginForm, RegisterForm, ForgetPasswordForm, ResetPasswordForm
from albumy.models import User
from albumy.settings import Operations
from albumy.utils import generate_token, validate_token, redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('Login success.', 'info')
                
                # Check if the user is a farmer and redirect accordingly
                if user.is_farmer:
                    return redirect(url_for('user.index', username=current_user.username))
                else:
                    return redirect(url_for('main.explore'))
                
            else:
                flash('Your account is blocked.', 'warning')
                return redirect(url_for('main.index'))
        flash('Invalid email or password.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/re-authenticate', methods=['GET', 'POST'])
@login_required
def re_authenticate():
    if login_fresh():
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        return redirect_back()
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        print(form.data)
        name = form.name.data
        email = form.email.data.lower()
        username = form.username.data
        password = form.password.data
        user = User(name=name, email=email, username=username)
        user.is_farmer = form.is_farmer.data
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)

@auth_bp.route('/forget-password', methods=['GET', 'POST'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)
            flash('Password reset email sent, check your inbox.', 'info')
            return redirect(url_for('.login'))
        flash('Invalid email.', 'warning')
        return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is None:
            return redirect(url_for('main.index'))
        if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD,
                          new_password=form.password.data):
            flash('Password updated.', 'success')
            return redirect(url_for('.login'))
        else:
            flash('Invalid or expired link.', 'danger')
            return redirect(url_for('.forget_password'))
    return render_template('auth/reset_password.html', form=form)

albumy/blueprints/main.py
# -*- coding: utf-8 -*-

import os
import random
from dotenv import load_dotenv
from urllib.parse import urlencode
import openai
import re
import requests
from flask import session
import re

from flask import render_template, flash, redirect, url_for, current_app, \
    send_from_directory, request, abort, Blueprint
from flask_login import login_required, current_user
from sqlalchemy.sql.expression import func

from albumy.decorators import permission_required
from albumy.extensions import db
from albumy.forms.main import DescriptionForm, TagForm, CommentForm
from albumy.models import User, Photo, Tag, Follow, Collect, Comment, Notification
from albumy.notifications import push_comment_notification, push_collect_notification
from albumy.utils import rename_image, resize_image, redirect_back, flash_errors

main_bp = Blueprint('main', __name__)

@main_bp.route('/index')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['ALBUMY_PHOTO_PER_PAGE']
        pagination = Photo.query \
            .join(Follow, Follow.followed_id == Photo.author_id) \
            .filter(Follow.follower_id == current_user.id) \
            .order_by(Photo.timestamp.desc()) \
            .paginate(page, per_page)
        photos = pagination.items
    else:
        pagination = None
        photos = None
    tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(func.count(Photo.id).desc()).limit(10)
    return render_template('main/index.html', pagination=pagination, photos=photos, tags=tags, Collect=Collect)

@main_bp.route('/')
@main_bp.route('/explore')
def explore():
    photos = Photo.query.order_by(func.random()).limit(12)
    return render_template('main/explore.html', photos=photos)


from google.cloud import vision_v1
from google.cloud.vision_v1 import types
from werkzeug.utils import secure_filename
import os

UPLOAD_FOLDER = 'uploads'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def get_ingredients_from_image(image_path, confidence_threshold=0.7):
    try:
        client = vision_v1.ImageAnnotatorClient()
        with open(image_path, 'rb') as image_file:
            content = image_file.read()
        image = types.Image(content=content)
        response = client.label_detection(image=image)
        
        common_fridge_items = set([
            "egg", "milk", "cheese", "yogurt", "butter", "bread", "chicken", "beef", 
            "pork", "fish", "tomato", "onion", "garlic", "lettuce", "spinach", "carrot", 
            "broccoli", "apple", "orange", "banana", "grape", "berry", "chocolate", "juice", 
            "water",
            # ... (expand this list as needed)
        ])

        detected_items = [
            label.description.lower() for label in response.label_annotations 
            if label.score >= confidence_threshold and label.description.lower() in common_fridge_items
        ]
        
        return detected_items
    
    except Exception as e:
        print(f"Error processing image: {e}")
        return ['eggs', 'tomatoes', 'spinach', 'milk']

load_dotenv()

# Initialize the OpenAI API with your key
openai.api_key = os.getenv("OPENAPI_KEY")

@main_bp.route('/make_meal', methods=['GET', 'POST'])
@login_required
def make_meal():
    recipe_details = None
    if request.method == 'POST':
        file = request.files['file']
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            filepath = os.path.join(UPLOAD_FOLDER, filename)
            file.save(filepath)
            ingredients = get_ingredients_from_image(filepath)
        else:
            ingredients = ['eggs', 'tomatoes', 'spinach', 'milk']
        description = request.form.get('description')

        initial_message = {
            "role": "user",
            "content": f"I have these in my fridge: {', '.join(ingredients)}. I want to make a {description}. Format: 'Ingredients:' followed by ingredients separated by '$', then 'Steps:' followed by the numbered steps separated by '$'."
        }

        gpt_response = run_conversation_with_gpt([initial_message])
        response_text = gpt_response.get('choices', [{}])[0].get('message', {}).get('content', '').strip()

        # Default empty lists
        ingredients_list = []
        instructions_list = []

        # Parsing
        if "Ingredients:" in response_text and "Steps:" in response_text:
            ingredients_text = response_text.split("Ingredients:")[1].split("Steps:")[0].strip()
            instructions_text = response_text.split("Steps:")[1].strip()

            # Split ingredients based on '$' symbol
            ingredients_list = [item.strip() for item in ingredients_text.split('$') if item.strip()]
            ingredients_list = [(i + " ✓") if i in ingredients else i for i in ingredients_list]
            
            # Split steps and remove any leading numbers followed by a dollar sign
            instructions_list = [re.sub(r"^\d+\.\s?", "", step).strip() for step in instructions_text.split('\n') if step.strip()]
        recipe_details = {
            'ingredients': ingredients_list,
            'instructions': instructions_list
        }
                
    return render_template('main/make_meal.html', recipe=recipe_details)

@main_bp.route('/help', methods=['GET'])
@login_required  # If you want to require the user to be logged in to access this route, otherwise, remove this line.
def help():
    return render_template('main/help.html')

def run_conversation_with_gpt(messages):
    # Set up the call to GPT-3.5-turbo-0613
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo-0613",
        messages=messages,
    )
    return response

@main_bp.route('/search')
def search():
    q = request.args.get('q', '').strip()
    if q == '':
        flash('Enter keyword about photo, user or tag.', 'warning')
        return redirect_back()

    category = request.args.get('category', 'photo')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_SEARCH_RESULT_PER_PAGE']
    if category == 'user':
        pagination = User.query.whooshee_search(q).paginate(page, per_page)
    elif category == 'tag':
        pagination = Tag.query.whooshee_search(q).paginate(page, per_page)
    else:
        pagination = Photo.query.whooshee_search(q).paginate(page, per_page)
    results = pagination.items
    return render_template('main/search.html', q=q, results=results, pagination=pagination, category=category)


@main_bp.route('/notifications')
@login_required
def show_notifications():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_NOTIFICATION_PER_PAGE']
    notifications = Notification.query.with_parent(current_user)
    filter_rule = request.args.get('filter')
    if filter_rule == 'unread':
        notifications = notifications.filter_by(is_read=False)

    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(page, per_page)
    notifications = pagination.items
    return render_template('main/notifications.html', pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if current_user != notification.receiver:
        abort(403)

    notification.is_read = True
    db.session.commit()
    flash('Notification archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/notifications/read/all', methods=['POST'])
@login_required
def read_all_notification():
    for notification in current_user.notifications:
        notification.is_read = True
    db.session.commit()
    flash('All notifications archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['ALBUMY_UPLOAD_PATH'], filename)


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
@permission_required('UPLOAD')
def upload():
    if request.method == 'POST' and 'file' in request.files:
        f = request.files.get('file')
        filename = rename_image(f.filename)
        f.save(os.path.join(current_app.config['ALBUMY_UPLOAD_PATH'], filename))
        filename_s = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['small'])
        filename_m = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['medium'])
        
        # Get additional form data
        location = request.form.get('location')
        quantity = request.form.get('quantity')
        produce_name = request.form.get('produce_name')
        price = request.form.get('price')
        
        photo = Photo(
            filename=filename,
            filename_s=filename_s,
            filename_m=filename_m,
            author=current_user._get_current_object(),
            location=location,  # Save location
            quantity=quantity,  # Save quantity
            produce_name=produce_name,  # Save produce_name
            price=price  # Save price
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')


@main_bp.route('/photo/<int:photo_id>')
def show_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(photo).order_by(Comment.timestamp.asc()).paginate(page, per_page)
    comments = pagination.items

albumy/templates/main/_comment.html
<div class="comments" id="comments">
    <h3>{{ photo.comments|length }} Comments
        <small>
            <a href="{{ url_for('.show_photo', photo_id=photo.id, page=pagination.pages or 1) }}#comment-form">latest</a>
        </small>
        {% if current_user == photo.author %}
            <form class="inline" method="post" action="{{ url_for('.set_comment', photo_id=photo.id) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-xs btn-link float-right">
                    {% if photo.can_comment %}Disable{% else %}Enable{% endif %} comment
                </button>
            </form>
        {% endif %}
    </h3>
    <hr>
    {% if comments %}
        {% for comment in comments %}
            <div class="comment">
                <div class="comment-thumbnail">
                    <a href="{{ url_for('user.index', username=comment.author.username) }}">
                        <img class="rounded img-fluid avatar-s profile-popover"
                             data-href="{{ url_for('ajax.get_profile', user_id=comment.author.id) }}"
                             src="{{ url_for('main.get_avatar', filename=comment.author.avatar_m) }}">
                    </a>
                </div>
                <div class="comment-body">
                    <h6>
                        <a class="profile-popover"
                           data-href="{{ url_for('ajax.get_profile', user_id=comment.author.id) }}"
                           href="{{ url_for('user.index', username=comment.author.username) }}">
                            {{ comment.author.name }}
                        </a>
                        {% if comment.author == photo.author %}
                            <span class="badge badge-light">Author</span>
                        {% endif %}
                        <small data-toggle="tooltip" data-placement="top" data-timestamp="{{ comment.timestamp }}"
                               data-delay="500">
                            {{ moment(comment.timestamp).fromNow(refresh=True) }}
                        </small>
                        {% if current_user.is_authenticated %}
                            <span class="float-right">
                            <span class="dropdown">
                                <button class="btn btn-sm btn-light" type="button" id="dropdownMenuButton"
                                        data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false">
                                <span class="oi oi-ellipses"></span>
                                </button>
                                <span class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                {% if current_user != comment.author %}
                                    <a class="dropdown-item btn"
                                       href="{{ url_for('.reply_comment', comment_id=comment.id) }}">
                                    <span class="oi oi-comment-square"></span> Reply
                                </a>
                                {% endif %}
                                {% if current_user == comment.author or current_user == photo.author or current_user.can('MODERATE') %}
                                    <a class="dropdown-item" data-toggle="modal" href="#!"
                                       data-href="{{ url_for('.delete_comment', comment_id=comment.id) }}"
                                       data-target="#confirm-delete">
                                    <span class="oi oi-trash" aria-hidden="true"></span> Delete
                                  </a>
                                {% endif %}
                                {% if current_user != comment.author %}
                                <form class="inline" method="post"
                                      action="{{ url_for('.report_comment', comment_id=comment.id) }}">
                                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                    <button type="submit" class="dropdown-item">
                                        <span class="oi oi-warning" aria-hidden="true"></span> Report
                                      </button>
                                </form>
                                {% endif %}
                                </span>
                                </span>
                            </span>
                        {% endif %}
                    </h6>
                    <p>
                        {% if comment.replied %}
                            Reply
                            <a href="{{ url_for('user.index', username=comment.replied.author.username) }}">{{ comment.replied.author.name }}</a>:
                        {% endif %}
                        {{ comment.body }}
                    </p>
                </div>
            </div>
            <hr>
        {% endfor %}
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    {% else %}
        <p class="tip">No comments.</p>
    {% endif %}

    {% if photo.can_comment %}
        {% if current_user.is_authenticated %}
            {% if current_user.can('COMMENT') %}
                {% if request.args.get('reply') %}
                    <div class="alert alert-dark">
                        Reply to {{ request.args.get('author') }}:
                        <a class="float-right" href="{{ url_for('.show_photo', photo_id=photo.id) }}">Cancel</a>
                    </div>
                {% endif %}
                <div class="comment-form-area">
                    <div class="comment-form-thumbnail">
                        <img class="rounded img-fluid avatar-s"
                             src="{{ url_for('main.get_avatar', filename=current_user.avatar_m) }}">
                    </div>
                    <div class="comment-form" id="comment-form">
                        {{ render_form(comment_form, action=url_for('.new_comment', photo_id=photo.id, page=pagination.pages or 1,
                        reply=request.args.get('reply')),
                        extra_classes="text-right") }}
                    </div>
                </div>
            {% else %}
                <p class="tip">
                    No permission.
                </p>
            {% endif %}
        {% else %}
            <p class="tip">
                <a href="{{ url_for('auth.login') }}">Login</a>
                or
                <a href="{{ url_for('auth.register') }}">Register</a> to leave a comment.
            </p>
        {% endif %}
    {% else %}
        <p class="tip">
            Comment disabled.
        </p>
    {% endif %}
</div>

albumy/templates/main/_photo_sidebar.html
{% from 'macros.html' import follow_area with context %}

<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link" href="{{ url_for('.photo_previous', photo_id=photo.id) }}">&larr;Previous</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{{ url_for('.photo_next', photo_id=photo.id) }}">Next&rarr;</a>
        </li>
    </ul>
</nav>
<div class="card bg-light mb-3 w-100 sidebar-card">
    <div class="card-body">
        <div class="row">
            <a href="{{ url_for('user.index', username=photo.author.username) }}">
                <img class="sidebar-avatar rounded avatar-m"
                     src="{{ url_for('main.get_avatar', filename=photo.author.avatar_m) }}">
            </a>
            <div class="sidebar-profile">
                <h6 class="card-title">
                    <a href="{{ url_for('user.index', username=photo.author.username) }}">{{ photo.author.name }}</a>
                </h6>
                <p class="card-subtitle mb-2 text-muted">{{ photo.author.username }}</p>
                {{ follow_area(photo.author) }}
            </div>
        </div>
    </div>
</div>

albumy/templates/main/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import photo_card with context %}

{% block title %}Home{% endblock %}

{% block content %}
{% if current_user.is_authenticated %}
    <div class="row justify-content-md-center">
        <div class="col-md-8">
            {% if photos %}
                {% for photo in photos %}
                    <div class="card mb-3 w-100 bg-light">
                        <div class="card-header">
                            <a class="dead-link" href="{{ url_for('user.index', username=photo.author.username) }}">
                                <img class="rounded img-fluid avatar-s profile-popover"
                                     data-href="{{ url_for('ajax.get_profile', user_id=photo.author.id) }}"
                                     src="{{ url_for('main.get_avatar', filename=photo.author.avatar_m) }}">
                            </a>
                            <a class="profile-popover trend-card-avatar"
                               data-href="{{ url_for('ajax.get_profile', user_id=photo.author.id) }}"
                               href="{{ url_for('user.index', username=photo.author.username) }}">{{ photo.author.name }}</a>
                            <span class="float-right">
                <small data-toggle="tooltip" data-placement="top" data-timestamp="{{ photo.timestamp }}"
                       data-delay="500">
                    {{ moment(photo.timestamp).fromNow(refresh=True) }}</small></span>
                        </div>
                        <div class="card-body">
                            <div class="" align="center">
                                <a class="thumbnail" href="{{ url_for('.show_photo', photo_id=photo.id) }}"
                                   target="_blank">
                                    <img class="img-fluid"
                                         src="{{ url_for('.get_image', filename=photo.filename_m) }}">
                                </a>
                            </div>
                        </div>
                        <div class="card-footer">
                            <span class="oi oi-star"></span>
                            <span id="collectors-count-{{ photo.id }}"
                                  data-href="{{ url_for('ajax.collectors_count', photo_id=photo.id) }}">
                                {{ photo.collectors|length }}
                            </span>
                            <span class="oi oi-comment-square"></span> {{ photo.comments|length }}
                            <div class="float-right">
                                {% if current_user.is_authenticated %}
                                    <button class="{% if not current_user.is_collecting(photo) %}hide{% endif %}
                                     btn btn-outline-secondary btn-sm uncollect-btn"
                                            data-href="{{ url_for('ajax.uncollect', photo_id=photo.id) }}"
                                            data-id="{{ photo.id }}">
                                        <span class="oi oi-x"></span> Uncollect
                                    </button>
                                    <button class="{% if current_user.is_collecting(photo) %}hide{% endif %}
                                     btn btn-outline-primary btn-sm collect-btn"
                                            data-href="{{ url_for('ajax.collect', photo_id=photo.id) }}"
                                            data-id="{{ photo.id }}">
                                        <span class="oi oi-star"></span> Collect
                                    </button>
                                {% else %}
                                    <form class="inline" method="post"
                                          action="{{ url_for('main.collect', photo_id=photo.id) }}">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-outline-primary btn-sm">
                                            <span class="oi oi-star"></span> Collect
                                        </button>
                                    </form>
                                {% endif %}
                            </div>
                            {% if photo.description %}
                                <p class="card-text">{{ photo.description }}</p>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="tip text-center">
                    <h3>No trends.</h3>
                    <p><a href="{{ url_for('.explore') }}">Explore</a></p>
                </div>
            {% endif %}
        </div>
        <div class="col-md-3">
            {% include 'main/_sidebar.html' %}
        </div>
    </div>
    {% if photos %}
        {{ render_pagination(pagination, align='center') }}
    {% endif %}
{% else %}
<div class="jumbotron" style="position: relative; background: url('{{ url_for('static', filename='images/top.GIF') }}') center center; background-size: contain; background-repeat: no-repeat; min-height: 100vh;">
    <div class="col-md-4 align-self-center" style="position: absolute; bottom: 20%; left: 50%; transform: translateX(-50%); text-align: center; background: rgba(255, 255, 255, 0.7); padding: 20px; border-radius: 10px;">
        <p><a class="btn btn-secondary btn-lg" href="{{ url_for('auth.register') }}">Join Now</a></p>
    </div>
</div>



{% endif %}
{% endblock %}